---
name: 'Renovate'
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      repoCache:
        description: 'Reset or disable the cache?'
        type: 'choice'
        default: 'enabled'
        options:
          - 'enabled'
          - 'disabled'
          - 'reset'

      renovateLogLevel:
        description: 'Renovate Log Level'
        type: 'choice'
        default: 'debug'
        options:
          - 'debug'
          - 'info'
          - 'warn'
          - 'error'
          - 'fatal'

# Declare default permissions as read only
permissions: 'read-all'

jobs:
  renovate:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write'
      pull-requests: 'write'
    steps:
      - name: 'Run Renovate'
        uses: 'renovatebot/github-action@b266b24b144602ed4f512f0773009d026722f4cc' # v40.2.6
        with:
          renovate-version: '38.52.2'
          configurationFile: '.github/renovate_global.js'
          token: '${{ secrets.renovate_token }}'
        env:
          RENOVATE_REPOSITORIES: '${{ github.repository }}'
          LOG_LEVEL: "${{ github.event.inputs.renovateLogLevel || 'debug' }}"
...
